const EXPO_PUBLIC_SUPABASE_URL = process.env.EXPO_PUBLIC_SUPABASE_URL;
const EXPO_PUBLIC_SUPABASE_KEY = process.env.EXPO_PUBLIC_SUPABASE_KEY

export const constant = {EXPO_PUBLIC_SUPABASE_KEY,EXPO_PUBLIC_SUPABASE_URL}